// Generated by CoffeeScript 1.4.0
(function() {
  var URL, WebSocketServer, mubsub, wss;

  WebSocketServer = require('ws').Server;

  URL = require('url');

  mubsub = require('mubsub');

  console.log("Waking the Weasel!");

  wss = new WebSocketServer({
    port: 7777
  });

  wss.on('connection', function(ws) {
    var channel, client, collection, db, id, query, resourceUrl, subscription, url, _ref;
    url = URL.parse(ws.upgradeReq.url);
    console.log("@ " + (URL.format(url)));
    _ref = url.pathname.replace(/^\//, '').split("/"), db = _ref[0], collection = _ref[1], id = _ref[2];
    if ((db != null) && (collection != null) && (id != null)) {
      resourceUrl = "/" + db + "/" + collection + "/" + id;
    } else if ((db != null) && (collection != null)) {
      resourceUrl = "/" + db + "/" + collection;
    } else {
      console.error("! " + url);
    }
    ws.on('message', function(doc) {
      console.log("> " + resourceUrl, doc);
      return channel.publish(JSON.parse(doc));
    });
    client = mubsub("mongodb://localhost:27017/" + db);
    channel = client.channel("" + collection + ".weasel");
    console.log("S " + resourceUrl);
    if (id) {
      query = {
        id: id
      };
    } else {
      query = {};
    }
    subscription = channel.subscribe({
      id: id
    }, function(doc) {
      var sendUpdate;
      sendUpdate = function() {
        console.log("< " + resourceUrl, doc);
        return ws.send(JSON.stringify(doc));
      };
      if (ws.readyState === 0) {
        return ws.on('open', sendUpdate);
      } else if (ws.readyState === 1) {
        return sendUpdate();
      } else if (ws.readyState === 2) {
        return console.warn("WebSocket is closing; cannot send update!");
      } else if (ws.readyState === 4) {
        return console.warn("WebSocket is closed; cannot send update!");
      } else {
        return console.error("WebSocket is in a weird state!", ws.readyState);
      }
    });
    return ws.on('close', function() {
      console.log("X " + resourceUrl);
      subscription.unsubscribe();
      return client.close();
    });
  });

}).call(this);
